name: Add issue to repo2

on:
  issues:
    types:
      - opened

jobs:
  add-issue-to-repo2:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: add_to_repo2
        with:
          # To find the ID, open the target repo, e.g. https://github.com/richkuz/repo2, right-click, View Page Source, search for data-type="repository"
          targetrepoid: "MDEwOlJlcG9zaXRvcnkzNTI2Mzc2Mjk"
          contentid: ${{ github.event.issue.node_id }}
          query: |
            mutation CreateIssue($targetrepoid:ID!) {
              createIssue(
                input: {
                  repositoryId: $targetrepoid,
                  title: "${{ github.event.issue.title }}",
                  #labelIds: ["2866102897"],
                  body: "Issue created in another repo, replicated here for visibility: ${{ github.event.issue.html_url }}"
                }
              ) {
                issue {
                  number
                  body
                }
              }
            }
        env:
          # The default GITHUB_TOKEN env var doesn't have enough scope.
          GITHUB_TOKEN: ${{ secrets.REPO2_CREATE_ISSUE_TOKEN }}
