name: Add issue to SDH project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-sdh-project:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: add_to_sdh_project
        with:
          projectid: "PVT_kwHOA7oDiM4AGyH3"
          contentid: ${{ github.event.issue.node_id }}
          query: |
            mutation add_to_project($projectid:ID!,$contentid:ID!) {
              addProjectV2ItemById(input:{projectId:$projectid contentId:$contentid}) {
                item {
                  id
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
