name: Issue Triage
on:
  issues:
    types: [labeled,unlabeled]
  pull_request:
    types: [labeled, unlabeled]
    
jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign labelled issues to projects
    steps:
      - name: Assign to repo and user projects
        uses: richkuz/garbage-actions/project-assigner@main
        id: project_assigner
        with:
          issue-mappings: |
            [
              {"label": "repo-project", "projectNumber": "1", "columnName": "To Do", "projectScope": "repo"},
              {"label": "user-project", "projectNumber": "1", "columnName": "To do", "projectScope": "user"}
            ]
          ghToken: ${{ secrets.MY_GITHUB_ACTIONS_TOKEN }}
